version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Trigger Netlify Build
          command: curl -X POST -d {} https://api.netlify.com/build_hooks/5f502d7b307755271bf17e2c

workflows:
  screenshot:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/install
      - cypress/run:
          store_artifacts: true
          requires:
            - cypress/install
      - deploy:
          requires:
            - cypress/run
